#pragma once

#include <trc/Types.h>
using namespace trc::basic_types;

class InvertibleAction
{
public:
    virtual ~InvertibleAction() noexcept = default;

    /**
     * @brief Execute the action.
     *
     * Does not have to be idempotent. Calling `apply` multiple times in a row
     * is not valid.
     */
    virtual void apply() = 0;

    /**
     * @brief Undo the action.
     *
     * Must be the inverse operation to `apply`.
     *
     * Does not have to be idempotent. Calling `undo` multiple times in a row
     * is not valid.
     */
    virtual void undo() = 0;
};

/**
 * @brief An execution strategy for actions.
 *
 * Decouples the input handling system from actions. Any details about actions
 * lies either in implementations of the `InvertibleAction` interface or in
 * implementations of `ActionExecutor`.
 *
 * `InputStateMachine` uses this interface to dispatch actions generated by
 * input commands.
 */
class ActionExecutor
{
public:
    virtual ~ActionExecutor() noexcept = default;

    virtual void execute(u_ptr<InvertibleAction> action) = 0;
};
