syntax = "proto3";
package trc.serial;

import "asset_reference.proto";
import "vector_types.proto";

message Rig
{
    message Relatives
    {
        optional uint32 parent = 1;
        repeated uint32 children = 2;
    }

    string name = 1;
    uint32 num_joints = 2;
    uint32 root_joint = 3;

    repeated Relatives relatives = 4;
    repeated string joint_name = 5;

    repeated mat4 inv_bind_pose_mat = 6;
    repeated mat4 local_joint_transform = 7;
    repeated mat4 global_joint_transform = 8;

    repeated AssetReference animations = 10;
}
