#version 460

layout (local_size_x = 10, local_size_y = 10) in;

layout (set = 0, binding = 0, rgba8) uniform image2D gBufferInputImages[3];
layout (set = 0, binding = 1, rgba8) uniform image2D rayTracingInputImages[1];

layout (set = 1, binding = 0) writeonly uniform image2D outputImage;

void main()
{
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec4 reflectColor = imageLoad(rayTracingInputImages[0], pixelCoords);
    imageStore(outputImage, pixelCoords, reflectColor);
}
