#pragma once

#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <variant>
#include <vector>

#include "BasicType.h"
#include "Capability.h"
#include "CodePrimitives.h"
#include "trc/Types.h"
#include "trc/util/Pathlet.h"

namespace trc::shader
{
    class ShaderModuleBuilder;
    struct CapabilityBuildContext;

    using CapabilityBuilder = std::function<code::Value(CapabilityBuildContext&)>;

    /**
     * @brief Defines an input/output interface for a single shader module
     *
     * Defines capabilities and resources.
     *
     * A resource is a plain description of a shader input. This may be one of
     *  - shader input attribute
     *  - descriptor set binding
     *  - push constant value
     *
     * Resources are identified by numerical IDs that are generated by the
     * `ShaderCapabilityConfig`.
     *
     * A capability is a possibly complex interface to one or more resources.
     * This may range from a simple access to an input attribute up to
     * complicated computations involving multiple resources and other
     * capabilites.
     *
     * Capabilities are identified by user-specified string identifiers.
     */
    class CapabilityConfig
    {
    public:
        struct DescriptorBinding
        {
            std::string setName;
            ui32 bindingIndex;

            // This is supposed to be set to 'buffer' or 'uniform sampler2D' or
            // something like that.
            std::string descriptorType;
            std::string descriptorName; // TODO: This one could can be generated
                                        // automatically, but then we can't rely
                                        // on the descriptor names anymore when
                                        // including code.

            // Makes the descriptor a descriptor array if specified.
            //
            // An array count of 0 means that the length is runtime dependent.
            std::optional<ui32> arrayCount{ std::nullopt };

            std::optional<std::string> layoutQualifier{ std::nullopt };
            std::optional<std::string> descriptorContent{ std::nullopt };
        };

        struct ShaderInput
        {
            BasicType type;
            ui32 location;
            bool flat{ false };
        };

        struct PushConstant
        {
            PushConstant(code::Type type, ui32 userId)
                : type(type), userId(userId) {}

            code::Type type;
            ui32 userId;
        };

        struct RayPayload
        {
            code::Type type;

            bool incoming{ false };

            // Is the payload a rayPayload or a callableData storage class?
            bool callableData{ false };
        };

        struct HitAttribute
        {
            BasicType type;
        };

        using Resource = std::variant<
            DescriptorBinding,
            ShaderInput,
            PushConstant,
            RayPayload,
            HitAttribute
        >;

        /** A resource and its additional requirements */
        struct ResourceData
        {
            Resource resourceType;
            std::string resourceMacroName;

            std::unordered_set<std::string> extensions;
            std::unordered_set<util::Pathlet> includeFiles;

            /** Maps [name -> value?] */
            std::unordered_map<std::string, std::optional<std::string>> macroDefinitions;
        };

        using ResourceID = ui32;

        void addGlobalShaderExtension(std::string extensionName);
        void addGlobalShaderInclude(util::Pathlet includePath);
        auto getGlobalShaderExtensions() const -> const std::unordered_set<std::string>&;
        auto getGlobalShaderIncludes() const -> const std::unordered_set<util::Pathlet>&;

        auto addResource(Resource shaderResource) -> ResourceID;
        void addShaderExtension(ResourceID resource, std::string extensionName);
        void addShaderInclude(ResourceID resource, util::Pathlet includePath);
        void addMacro(ResourceID resource, std::string name, std::optional<std::string> value);

        /**
         * @brief Create an accessor for a resource.
         *
         * Returns an expression that evaluates to a resource.
         */
        auto accessResource(ResourceID resource, ShaderModuleBuilder& builder) const
            -> code::Value;

        auto getResourceInfo(ResourceID resource) const -> const ResourceData&;

        /**
         * Implement a capability as a direct resource access.
         */
        void linkCapability(Capability capability, ResourceID resource);

        /**
         * It is allowed to reference other capabilites from inside the builder
         * function by calling `ShaderModuleBuilder::makeCapabilityAccess` on
         * the build context's builder.
         */
        void linkCapability(Capability capability, CapabilityBuilder factory);

        /**
         * @return bool True if this capability configuration implements
         *              `capability`.
         */
        bool hasCapability(Capability capability) const;

        /**
         * @brief Create an accessor for a capability.
         *
         * Creates an expression that evaluates to a capability's value.
         *
         * This may be just an identifier, or a more complex expression like an
         * array access, a computation, or a function call, depending on the
         * capability's implementation.
         *
         * @return A list of resources that are accessed by the capability's
         *         implementation.
         *
         * @throw std::out_of_range if `capability` is not defined at this
         *        capability config.
         */
        auto accessCapability(Capability capability, ShaderModuleBuilder& builder) const
            -> std::pair<code::Value, std::vector<ResourceID>>;

    private:
        static auto makeCapabilityBuilderFromResource(ResourceID resource) -> CapabilityBuilder;

        std::unordered_set<std::string> globalExtensions;
        std::unordered_set<util::Pathlet> globalIncludes;

        /** `ResourceID` is an index into this array. */
        std::vector<s_ptr<ResourceData>> resources;

        std::unordered_map<Capability, CapabilityBuilder> capabilityImpls;
    };

    struct CapabilityBuildContext
    {
        ShaderModuleBuilder& builder;

        auto accessResource(CapabilityConfig::ResourceID resourceID) -> code::Value;

    private:
        friend class CapabilityConfig;
        CapabilityBuildContext(const CapabilityConfig* conf, ShaderModuleBuilder& builder)
            : builder(builder), conf(conf)
        {}

        const CapabilityConfig* conf;
        std::unordered_set<CapabilityConfig::ResourceID> accessedResources;
    };
} // namespace trc::shader
